/**
 * Google Gemini Imagen image provider.
 *
 * Uses the Gemini API REST endpoint with Imagen 3 model.
 * Generates images via the generateContent endpoint with IMAGE modality.
 */

import type {
  ImageProvider,
  ImageGenerationRequest,
  GeneratedImage,
  ProviderHealth,
} from "@frame/core";

interface GeminiResponse {
  candidates?: Array<{
    content?: {
      parts?: Array<{
        text?: string;
        inlineData?: {
          mimeType: string;
          data: string;
        };
      }>;
    };
  }>;
  error?: {
    code: number;
    message: string;
  };
}

export class GeminiImageProvider implements ImageProvider {
  name = "gemini";
  private apiKey: string;

  constructor(apiKey: string) {
    this.apiKey = apiKey;
  }

  async generate(request: ImageGenerationRequest): Promise<GeneratedImage> {
    // Use Gemini 2.0 Flash with image generation capability
    const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=${this.apiKey}`;

    const res = await fetch(url, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        contents: [
          {
            parts: [
              {
                text: `Generate a high-quality landscape image (16:9 aspect ratio) based on this description: ${request.prompt}`,
              },
            ],
          },
        ],
        generationConfig: {
          responseModalities: ["TEXT", "IMAGE"],
        },
      }),
    });

    if (!res.ok) {
      const err = await res.text();
      throw new Error(`Gemini API error ${res.status}: ${err}`);
    }

    const data = (await res.json()) as GeminiResponse;

    if (data.error) {
      throw new Error(`Gemini API error: ${data.error.message}`);
    }

    // Find the image part in the response
    const parts = data.candidates?.[0]?.content?.parts;
    if (!parts) {
      throw new Error("No content in Gemini response");
    }

    const imagePart = parts.find((p) => p.inlineData);
    if (!imagePart?.inlineData) {
      throw new Error(
        "No image generated by Gemini. Response contained only text.",
      );
    }

    const mimeType = imagePart.inlineData.mimeType as
      | "image/jpeg"
      | "image/png";

    return {
      data: Buffer.from(imagePart.inlineData.data, "base64"),
      mimeType: mimeType === "image/jpeg" ? "image/jpeg" : "image/png",
      width: request.width,
      height: request.height,
      provider: this.name,
      generatedAt: new Date().toISOString(),
    };
  }

  async healthCheck(): Promise<ProviderHealth> {
    const start = Date.now();
    try {
      const res = await fetch(
        `https://generativelanguage.googleapis.com/v1beta/models?key=${this.apiKey}`,
      );
      return {
        provider: this.name,
        status: res.ok ? "healthy" : "degraded",
        lastChecked: new Date().toISOString(),
        latencyMs: Date.now() - start,
        message: res.ok ? "Gemini API accessible" : `HTTP ${res.status}`,
      };
    } catch (err) {
      return {
        provider: this.name,
        status: "failed",
        lastChecked: new Date().toISOString(),
        latencyMs: Date.now() - start,
        message: err instanceof Error ? err.message : "Unknown error",
      };
    }
  }
}
